name: Install Cross compilation prerequisites
description: Install the prerequisites for cross compilation, where supported FOR LINUX ONLY and ONLY FOR ASCIIDOCTOR-SERVER

inputs:
  rust_target:
    description: 'The target triple for the cross compilation'
    required: true

runs:
  using: "node20"
  main: "dist/index.js"