name: Install Cross compilation prerequisites
description: Install the prerequisites for cross compilation, where supported FOR LINUX ONLY and ONLY FOR ASCIIDOCTOR-SERVER

inputs:
  rust_target:
    description: 'The target triple for the cross compilation'
    required: true
outputs:
  linker:
    description: 'The linker for the target triple'
    value: ${{ steps.main.outputs.linker }}
  package_arch:
    description: 'The debian name for the architecture'
    value: ${{ steps.main.outputs.package_arch }}

runs:
  using: "composite"
  steps:
    - if: ${{ ( ! contains(inputs.rust_target, '-unknown-linux-') ) || runner.os != 'Linux' }}
      run: |
        echo "Cross compilation is only supported for Linux targets."
        exit 1
      shell: bash
    - name: Install cross compilation prerequisites
      id: main
      shell: bash
      run: ./index.sh ${{ inputs.rust_target }}