name: Test

on:
  push:
    tags: ['v*']
    branches:
      - "main"
  pull_request:
  workflow_dispatch:


jobs:
  test:
    name: ${{ matrix.job.target }}
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: test_fixture } }
    strategy:
      fail-fast: false
      matrix:
        target:
          - aarch64-unknown-linux-gnu
          - aarch64-unknown-linux-musl
          - arm-unknown-linux-gnueabihf
          - arm-unknown-linux-musleabihf
          - i686-unknown-linux-musl
          - i686-unknown-linux-gnu
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup cross compilation
        uses: .
        id: cross
        with:
          rust_target: ${{ matrix.target }}
      - name: Install Rust toolchain
        id: rust-toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - name: Build
        run: cargo run --frozen --locked --offline --target=${{ matrix.job.target }}
        env:
          RUSTFLAGS: -C linker=${{ steps.cross.outputs.linker }}
